// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gldjwkhvzbsfnzjaopsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZGp3a2h2emJzZm56amFvcHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MDgyODMsImV4cCI6MjA0OTM4NDI4M30.7aAsHU_fIBxmbdGSlfGGIRNu5snk5ow37XxS6QYO3x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);